#!/bin/bash

# bgcolor="#282828"
# gray="#928374"
# white="#fbf1c7"
# red="#fb4934"
# darkred="#cc241d"
# green="#b8bb26"
# yellow="#fabd2f"
# orange="#fe8019"
# blue="#458588"
# darkblue="#076678"
# magenta="#d3869b"
# cyan="#8ec07c"
# darkgray="#504945"

bgcolor="#282c34"
gray="#abb2bf"
white="#e5e7eb"
red="#e06c75"
darkred="#be5046"
green="#98c379"
yellow="#e5c07b"
orange="#d19a66"
blue="#61afef"
darkblue="#437aa7"
magenta="#c678dd"
cyan="#56b6c2"
darkgray="#494f59"

function i3block () {
    font=${4:-"Ubuntu Nerd Font 12"}
    echo "<span background='$1' foreground='$bgcolor'> $2 </span><span background='$darkgray' foreground='$white' font='$font'> $3 </span>"
    return 0
}
