#!/bin/bash

bgcolor="#1d2021"
gray="#928374"
white="#fbf1c7"
red="#ea6962"
darkred="#be5046"
green="#a9b665"
yellow="#d8a657"
orange="#e78a4e"
blue="#7daea3"
darkblue="#437aa7"
magenta="#d3869b"
cyan="#89b482"
darkgray="#514944"

function i3block () {
    font=${4:-"Ubuntu Nerd Font 12"}
    echo "<span background='$1' foreground='$bgcolor'> $2 </span><span background='$darkgray' foreground='$white' font='$font'> $3 </span>"
    return 0
}
