#!/bin/bash

case $BLOCK_BUTTON in
    1) pactl set-sink-volume @DEFAULT_SINK@ toggle && pkill -RTMIN+1 i3blocks;;
    3) fix-mic && notify-send "Mic Enabled" "Bluetooth Mic connected successfully!!";;
    *) ;;
esac

source ~/.config/i3/i3colors
# volinfo=$(awk -F"[][]" '/Left:/ {print $2, $4}' <(amixer -D pulse sget Master | sed 's/%//'))
# vol=$(echo $volinfo | cut -d " " -f1)
# mute=$(echo $volinfo | cut -d " " -f2)

vol=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F "/" '{print $2}' | sed 's/[ %]//g')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk -F ": " '{print $2}')

if [[ $mute == "yes" ]];then
    icon="婢"
elif [[ $vol -ge 70 ]];then
    icon="墳"
elif [[ vol -ge 30 ]];then
    icon="奔"
elif [[ vol -ge 10 ]];then
    icon=" "
fi

i3block $red $icon "$vol%"
