#!/usr/bin/env bash

theme="style-launcher"
dir="$HOME/.config/rofi/styles"
source ~/.config/i3/i3colors

# dark
ALPHA="#00000000"
BG="${bgcolor}ff"
FG="${white}ff"
SELECT="${darkgray}ff"

ACCENT="${magenta}ff"

cat > $dir/colors-launcher.rasi <<- EOF
	/* colors */
	* {
	  al:  $ALPHA;
	  bg:  $BG;
	  se:  $SELECT;
	  fg:  $FG;
	  ac:  $ACCENT;
	}
EOF

rofi -no-lazy-grab -show drun -modi drun -theme $dir/"$theme"
