#!/usr/bin/env bash

layoutopts="MonadTall (mainLeft)#
vmv (mainCenter)#
mc (mainCenter)#
mainCenter#
snr (SmartNestedRight)#
SmartNestedRight#
nr (NestedRight)#
NestedRight#
vtb (VerticalTileBottom)#
VerticalTileBottom#
vtt (VerticalTileTop)#
VerticalTileTop#
matrix#
mvm (MainVStackMain)#
MainVStackMain#
mmv (MainMainVStack)#
MainMainVStack#
MonadTallFlip (mainRight)#
vm (mainRight)#
mr (mainRight)#
mainRight#
mv (mainLeft)#
ml (mainLeft)#
mainLeft#
tabbed#
maxTabbed (max)#
max#
3h (h3Stack)#
3r (h3Stack)#
3row (h3Stack)#
h3Stack#
3v (v3Stack)#
3c (v3Stack)#
3col (v3Stack)#
v3Stack#
2h (h2Stack)#
2r (h2Stack)#
2row (h2Stack)#
h2Stack#
2v (v2Stack)#
2c (v2Stack)#
2col (v2Stack)#
v2Stack#
1r (hStack)#
1row (hStack)#
hStack#
1c (vStack)#
1col (vStack)#
vStack"

layoutlist=$(echo $layoutopts | sed 's/# /\\n/g')
selected_layout=$(bash ~/.config/rofi/search_prompt "$layoutlist" "Layout")
echo $selected_layout

if [[ "$selected_layout" == "" ]];then
    exit 0
fi

i3-instant-layout $selected_layout






